### ISSUE TITLE
ally.disengage re-enables previously disabled elements

### ISSUE THREAD

**Issue by ryan-ludwig** [medialize/ally.js#123]
You have 2 inputs, one has a disabled attribute by default.
You call ally.maintain.disabled().
Both inputs are now disabled.
You call ally.disengage().
Both inputs are now enabled.

The problem is that the input that was disabled by default needs to remain disabled after ally.disengage.
https://jsbin.com/fotejizolo/1/edit?html,css,js,output

**Comment by jordanaustin** [comment]
@rodneyrehm we may have an easier time fixing this now with the inertElementCache. I don't think we need to add the element to the inertElementCache if it was already inert, because then when disengage is called we can just disengage elements that Ally made inert.

Thoughts?

**Comment by jordanaustin** [comment]
@rodneyrehm I tested this in maintain/disabled.js renderInert method and it seems fix the issue, not sure if there's something else that would need to be done to cover other inert cases: 


    if (!element.disabled && !element.inert) {
      this._inertElementCache.push(element);
      makeElementInert(element);
    }

**Comment by rodneyrehm** [comment]
Where's `element.inert` coming from? You'd probably want to switch the condition to use [`ally.is.disabled`](http://allyjs.io/api/is/disabled.html) instead, to make sure that the fix does not only apply to form controls, but all disabled elements.

**Comment by jordanaustin** [comment]
I'm not sure that element.inert is a thing in any browsers yet. The most basic need is that we need to protect against is a form element that is :disabled before maintain.disabled was engaged. I don't think ally needs to deal with the element if it was already disabled. Does that sound right?

**Comment by rodneyrehm** [comment]
1. An element is "disabled" if it has disabled property set to true (form controls), or if it has the attribute `data-ally-disabled` (everything else).
2. An element that is disabled at the time of engaging `ally.maintain.disabled` should not be disabled again, and should not be enabled upon disengaging `ally.maintain.disabled`.
3. The MutationObserver should identify elements that became enabled in case they were not disabled because of 2 (i.e. listen to the attributes `disabled` and `data-ally-disabled` in addition to `tabindex`)
