### ISSUE TITLE
Focus should be completely trapped within the dialog

### ISSUE THREAD

**Issue by becka11y** [medialize/ally.js#63]
In the current implementation I can tab out of the dialog and into the browser controls.  I saw your statement in the dialog tutorial, 
"by redirecting focus to stay within the dialog it becomes impossible to reach the browser's UI by pressing Tab, so we're breaking native browser behavior"

Since this is essentially an application, I think it is okay to remove the browser controls from the focus ring when the dialog is present.  I believe a screen reader user would be very confused if they pressed tab within a dialog and ended back at the browser controls. They would either have to shift-tab IF they realized focus was in the browser and hope focus went back to the dialog. OR they would have to keep pressing tab several more times to end up in the dialog.  I think that model is confusing.

**Comment by rodneyrehm** [comment]
The [`<dialog>` element](http://www.w3.org/TR/html51/semantics.html#the-dialog-element) (proposed in HTML5.1 and currently implemented in Google Chrome) behaves just like that. Focus is limited to the dialog and the browser UI. Hit the "open modal dialog" button on this [demo page](http://demo.agektmr.com/dialog/).

Every JavaScript driven dialog has had the limitation of *having to* trap focus in a way that would prevent the browser UI from receiving focus. Unless everything outside of the dialog was set to `visibility: hidden;`, but I've never seen anyone do that.

I'd argue that *technical constraints* appear to have created a defacto standard behavior on the web. Your argument seems to go in the same direction: screen reader users would not expect any other behavior than what their used to.

However, my experience is that none of this applies to the iPhone and VoiceOver. On this device the focus state is quasi irrelevant to navigation. VoiceOver has its own focus indication (whatever that's called) that is not bound by what's focusable, only by what's visible. And you can very well advance focus to the browser UI, right out of an open modal dialog.

**Comment by rodneyrehm** [comment]
Some voices on twitter agreeing with @becka11y:

> [@patrick_h_lauke says](https://twitter.com/patrick_h_lauke/status/667865840365211652): As long as you're not trying to block any other means of escaping (e.g. ALT+D or F6 to focus URL bar, i'd say yes [to not pass focus to browser UI].

---

> [@LeonieWatson says](https://twitter.com/LeonieWatson/status/668456005710254082): Dialogue should be dismissed before k'board access to browser UI is available IMO.

**Comment by rodneyrehm** [comment]
Some more voices on twitter agreen with @becka11y 

> [@yatil says](https://twitter.com/yatil/status/668485225207488512) My gut feeling agrees. How is this handles in standard alert/confirm JavaScript dialogs?

---

> [@patrick_h_lauke says](https://twitter.com/patrick_h_lauke/status/668497539956633600) compare it to the behavior of, say, alert() or confirm() - it traps focus inside the dialog box itself, completely

---

> [@MarcoZehe says](https://twitter.com/MarcoZehe/status/668690155411238912): I agree. A modal dialog is important enough that it needs to be acted upon first.

**Comment by rodneyrehm** [comment]
I see an overwhelming support for preventing focus to reach the browser UI. The question now is how we go about fixing this.

As far as I understand focus traverses to the browser UI on <kbd>Tab</kbd> and <kbd>Shift Tab</kbd> only. Given that we can identify the first and last keyboard focusable element quite accurately (`ally.query.tabsequence`), we should be able to loop around.

This should become a new service `ally.maintain.focusInDocument` (better name?), to keep the service `ally.maintain.disabled` doing only one thing. We should also be able to use this new service within Chrome's `<dialog>` element to "fix" their behavior.

**Comment by marcysutton** [comment]
:tada: Props for surveying support. I had heard both opinions, so it's good to finally pick a direction for trapping focus. 

I love the service idea for usability, and for making HTML5 `<dialog>` better. I know Chrome's implementation and its polyfill were both missing a few things last I checked (dialog role, focus management on close).

**Comment by rodneyrehm** [comment]
ok then, bumping the discussion to feature request. We may want to wait for #59 (possibly also #6, #5) to land before tackling this.

**Comment by rodneyrehm** [comment]
What should we call this module?

* `ally.maintain.focusInDocument`
* `ally.maintain.documentFocus` (current working name)
* `ally.maintain.tabFocus`
* `ally.maintain.tabsequence`
* `ally.when.tabKey`
* ???

The module only concerns itself with the <kbd>Tab</kbd> key. It doesn't do more than register `ally.when.key({ '?shift+tab': callback })` and run `ally.query.tabsequence` to wrap around the edges.

I think I'd like "tab" (possibly even "key") to be in the name. I'm not sure if `ally.maintain` is the correct namespace for this, which is why I added `ally.when.tabKey` to the list. Opinions, anyone?

**Comment by rodneyrehm** [comment]
… went with `ally.maintain.tabFocus`

**Comment by robdodson** [comment]
From a security perspective I'm concerned about focus trapping not allowing the user to escape to the browser UI, especially if they want to close the tab.

Recently [the Chromium team mentioned that they're encouraging folks not to use `alert()`](https://developers.google.com/web/updates/2017/03/dialogs-policy), because it forces the user to take an action without an easy means of escape. This has lead to [situations which harm users](https://blog.malwarebytes.com/cybercrime/2013/12/android-pop-ups-warn-of-infection/).

While a user _may_ use keyboard shortcuts like CMD+L or explore by touch to escape a modal, I'm not sure if we want to solely rely on those methods.

cc @avidrissman @alice
