### ISSUE TITLE
Errors and warnings in Chrome

### ISSUE THREAD

**Issue by jonathanp** [medialize/ally.js#68]
I get the following errors and warnings in my console (Chrome v46.0.2490.86 on OS X) when running `ally.js`...

<img width="685" alt="screen shot 2015-11-22 at 09 40 48" src="https://cloud.githubusercontent.com/assets/76098/11324350/3ec4bea0-90fd-11e5-9c64-281aba37d31c.png">

**Comment by rodneyrehm** [comment]
Unfortunately we won't get rid of these errors any time soon. See [Supports API](http://allyjs.io/api/supports.html#Console-warnings) for an explanation. The `net::ERR_INVALID_URL` errors are irrelevant (caused by invalid DataURIs). The `/deep/ combinator` warning is deceptive, because `/deep/` is [remains supported in the static profile](https://twitter.com/tabatkins/status/624254124398243840) (used by `querySelector()` et al). See [Dynamic vs Static Selector Profiles](https://drafts.csswg.org/selectors-4/#profiles) and [CSS Scoping Module](https://drafts.csswg.org/css-scoping/#deep-combinator).

Do we need to make that clearer in the docs?

**Comment by rodneyrehm** [comment]
It turns out we can get rid of the `net:ERR_INVALID_URL` messages by providing a valid data uri that doesn't satisfy the expected media type. This way we don't have to add dummy `mp3` and `mp4` payload to the code base…

**Comment by jonathanp** [comment]
Sounds good! :+1:
